### ISSUE TITLE
Compile with GCC 4.4.7 fails on GCC diagnostics

### ISSUE THREAD

**Issue by viblo** [rainycape/magick#3]
When I try to compile with graphicsmagic and GCC 4.4.7 it fails because it doesnt support GCC diagnostic inside functions:

```
➜ go install -tags=gm ./...
# github.com/rainycape/magick
github.com/rainycape/magick/color.c: In function ‘calculate_image_entropy_rect’:
github.com/rainycape/magick/color.c:34: error: #pragma GCC diagnostic not allowed inside functions
github.com/rainycape/magick/color.c:36: error: #pragma GCC diagnostic not allowed inside functions
```

If I remove those two pragmas it works fine. It also compiles perfectly fine on my OSX box with GCC 4.2.1 using ImageMagick.
